#!/bin/sh
# run this script after making changes to documentation
asciidoctor -a docinfo=shared ./doc/*.adoc
w3m ./doc/alterfund.html | head -n -1 > ./cmd/ccd/doc/alterfund.txt
w3m ./doc/alterproject.html | head -n -1 > ./cmd/ccd/doc/alterproject.txt
w3m ./doc/alterset.html | head -n -1 > ./cmd/ccd/doc/alterset.txt
w3m ./doc/altertrack.html | head -n -1 > ./cmd/ccd/doc/altertrack.txt
w3m ./doc/createfilter.html | head -n -1 > ./cmd/ccd/doc/createfilter.txt
w3m ./doc/createfund.html | head -n -1 > ./cmd/ccd/doc/createfund.txt
w3m ./doc/createproject.html | head -n -1 > ./cmd/ccd/doc/createproject.txt
w3m ./doc/createset.html | head -n -1 > ./cmd/ccd/doc/createset.txt
w3m ./doc/createtrack.html | head -n -1 > ./cmd/ccd/doc/createtrack.txt
w3m ./doc/createuser.html | head -n -1 > ./cmd/ccd/doc/createuser.txt
w3m ./doc/delete.html | head -n -1 > ./cmd/ccd/doc/delete.txt
w3m ./doc/dropfilter.html | head -n -1 > ./cmd/ccd/doc/dropfilter.txt
w3m ./doc/dropfund.html | head -n -1 > ./cmd/ccd/doc/dropfund.txt
w3m ./doc/dropproject.html | head -n -1 > ./cmd/ccd/doc/dropproject.txt
w3m ./doc/dropset.html | head -n -1 > ./cmd/ccd/doc/dropset.txt
w3m ./doc/droptrack.html | head -n -1 > ./cmd/ccd/doc/droptrack.txt
#w3m ./doc/info.html | head -n -1 > ./cmd/ccd/doc/info.txt
w3m ./doc/insert.html | head -n -1 > ./cmd/ccd/doc/insert.txt
w3m ./doc/select.html | head -n -1 > ./cmd/ccd/doc/select.txt
w3m ./doc/show.html | head -n -1 > ./cmd/ccd/doc/show.txt
w3m ./doc/update.html | head -n -1 > ./cmd/ccd/doc/update.txt
