// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"strings"

	"github.com/indexdata/ccms/cmd/ccd/ast"
)

type yySymType struct {
	yys      int
	node     ast.Node
	str      string
	nodeList []ast.Node
}

const GT_OR_EQUAL = 57346
const LT_OR_EQUAL = 57347
const NOT_EQUAL = 57348
const ADD = 57349
const ALL = 57350
const ALTER = 57351
const AND = 57352
const ARCHIVE = 57353
const ARCHIVED = 57354
const ASC = 57355
const BY = 57356
const CREATE = 57357
const COUNT = 57358
const DELETE = 57359
const DESC = 57360
const DROP = 57361
const ENCRYPTED = 57362
const FILTER = 57363
const FROM = 57364
const FUND = 57365
const ILIKE = 57366
const IN = 57367
const INFO = 57368
const INSERT = 57369
const INTO = 57370
const LIKE = 57371
const LIMIT = 57372
const NOT = 57373
const NULL = 57374
const OFFSET = 57375
const OR = 57376
const ORDER = 57377
const PASSWORD = 57378
const PROJECT = 57379
const PROJECTS = 57380
const PROPERTY = 57381
const PING = 57382
const RETRIEVE = 57383
const SELECT = 57384
const SET = 57385
const SHOW = 57386
const TAG = 57387
const TO = 57388
const UPDATE = 57389
const USER = 57390
const VERSION = 57391
const WHERE = 57392
const WITH = 57393
const IDENT = 57394
const NUMBER = 57395
const SLITERAL = 57396

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"GT_OR_EQUAL",
	"LT_OR_EQUAL",
	"NOT_EQUAL",
	"ADD",
	"ALL",
	"ALTER",
	"AND",
	"ARCHIVE",
	"ARCHIVED",
	"ASC",
	"BY",
	"CREATE",
	"COUNT",
	"DELETE",
	"DESC",
	"DROP",
	"ENCRYPTED",
	"FILTER",
	"FROM",
	"FUND",
	"ILIKE",
	"IN",
	"INFO",
	"INSERT",
	"INTO",
	"LIKE",
	"LIMIT",
	"NOT",
	"NULL",
	"OFFSET",
	"OR",
	"ORDER",
	"PASSWORD",
	"PROJECT",
	"PROJECTS",
	"PROPERTY",
	"PING",
	"RETRIEVE",
	"SELECT",
	"SET",
	"SHOW",
	"TAG",
	"TO",
	"UPDATE",
	"USER",
	"VERSION",
	"WHERE",
	"WITH",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"';'",
	"'*'",
	"'('",
	"')'",
	"'='",
	"'<'",
	"'>'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 228

var yyAct = [...]uint8{
	112, 162, 107, 103, 68, 161, 108, 104, 101, 84,
	182, 180, 135, 134, 181, 181, 203, 202, 201, 200,
	122, 121, 165, 119, 91, 137, 136, 71, 70, 116,
	48, 52, 55, 92, 76, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 73, 211, 67, 44, 43, 22,
	50, 23, 210, 130, 74, 24, 209, 25, 208, 26,
	195, 194, 193, 207, 192, 110, 27, 28, 132, 133,
	90, 129, 191, 179, 72, 106, 128, 75, 96, 110,
	32, 166, 29, 47, 30, 142, 51, 31, 118, 111,
	49, 51, 100, 175, 120, 21, 51, 114, 113, 123,
	117, 115, 150, 111, 95, 94, 127, 89, 87, 86,
	51, 114, 113, 206, 131, 115, 82, 81, 80, 79,
	66, 139, 143, 145, 138, 56, 205, 204, 197, 151,
	153, 154, 155, 156, 152, 185, 178, 163, 163, 157,
	158, 159, 160, 164, 53, 54, 146, 144, 174, 176,
	177, 51, 97, 83, 173, 172, 171, 148, 170, 51,
	85, 77, 41, 88, 36, 98, 51, 51, 42, 149,
	186, 187, 188, 189, 190, 93, 35, 34, 37, 124,
	51, 51, 163, 196, 38, 184, 141, 125, 168, 39,
	45, 69, 40, 147, 99, 198, 126, 169, 78, 4,
	199, 1, 109, 33, 105, 102, 183, 167, 140, 46,
	19, 18, 17, 16, 20, 15, 14, 13, 12, 11,
	10, 9, 8, 7, 6, 3, 5, 2,
}

var yyPact = [...]int16{
	40, -1000, -1000, 40, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 140, 139, 141, 170, 125, -7, 162, 34,
	107, 99, 70, -1000, 99, 99, 99, 99, 99, 99,
	99, 99, 99, -1000, 65, 99, 169, -29, -1000, -1000,
	-30, -1000, 19, 99, 22, 118, -1000, 189, 64, 63,
	62, 61, 102, 110, 54, 53, -1000, 121, 52, 99,
	-34, -23, -1000, 138, 50, -1000, 49, 129, 126, -1000,
	-1000, -1000, -1000, 174, 37, 44, -1000, -1000, -27, -1000,
	110, 33, -35, 99, -1000, -1000, -38, -39, 99, 143,
	-1000, -1000, 153, 186, -1000, 47, 44, 8, -1000, -1000,
	-31, -32, -1000, -1000, -1000, 44, 169, 151, -1000, -1000,
	30, 115, 114, 150, 48, 44, 44, 58, 58, 58,
	58, -1000, 58, 58, 58, 58, 99, 99, -36, 26,
	158, 183, -1000, 108, 106, 105, 104, 39, 99, 128,
	18, 186, -1000, 8, 8, 8, 8, -1000, -1000, -1000,
	-1000, -47, -1000, -1000, -48, -1000, -1000, 152, 82, 99,
	99, 99, 99, 99, 17, 9, 7, 6, 5, -1000,
	-1000, 99, -1000, -1000, 75, -1000, 182, -40, -41, -42,
	-43, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	74, 73, 60, 10, 3, 1, -3, -10, -1000, -1000,
	-1000, -1000,
}

var yyPgo = [...]uint8{
	0, 227, 226, 199, 225, 224, 223, 222, 221, 220,
	219, 218, 217, 216, 215, 214, 213, 212, 211, 210,
	209, 4, 9, 208, 207, 206, 8, 205, 3, 204,
	2, 7, 6, 202, 5, 1, 0, 201,
}

var yyR1 = [...]int8{
	0, 37, 1, 4, 4, 3, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 6, 5, 5, 5, 5, 5, 7, 8,
	9, 10, 11, 12, 13, 14, 14, 16, 15, 17,
	17, 18, 18, 18, 18, 18, 19, 19, 19, 19,
	20, 20, 20, 21, 22, 22, 23, 23, 23, 23,
	24, 24, 25, 25, 26, 27, 27, 28, 28, 31,
	31, 29, 29, 29, 29, 29, 30, 30, 30, 30,
	30, 32, 32, 32, 33, 33, 33, 33, 34, 34,
	35, 36,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 9, 9, 9, 9, 9, 4, 4,
	4, 8, 5, 4, 4, 2, 3, 7, 2, 4,
	5, 3, 6, 4, 3, 4, 11, 11, 11, 11,
	1, 1, 4, 6, 2, 0, 3, 4, 4, 0,
	2, 0, 2, 0, 1, 1, 3, 1, 3, 1,
	2, 1, 3, 3, 3, 3, 1, 3, 3, 3,
	3, 1, 4, 4, 1, 1, 1, 3, 1, 3,
	1, 1,
}

var yyChk = [...]int16{
	-1000, -37, -1, -4, -3, -2, -5, -6, -7, -8,
	-9, -10, -11, -12, -13, -14, -16, -17, -18, -19,
	-15, 55, 9, 11, 15, 17, 19, 26, 27, 42,
	44, 47, 40, -3, 37, 37, 23, 37, 43, 48,
	22, 37, 43, 55, 54, 28, -20, 49, -36, 56,
	16, 52, -36, 37, 38, -36, 55, -36, -36, -36,
	-36, -36, -36, -36, -36, -36, 55, -36, -21, 22,
	57, 57, 55, 25, -36, 55, 12, 43, 9, 55,
	55, 55, 55, 51, -22, 50, 55, 55, 42, 55,
	-36, 58, 56, 37, 55, 55, -36, 23, 39, 20,
	55, -26, -27, -28, -31, -29, 31, -30, -32, -33,
	21, 45, -36, 54, 53, 57, 56, -22, 55, 58,
	-36, 59, 59, -36, 36, 34, 10, 59, 29, 24,
	6, -31, 60, 61, 5, 4, 57, 57, -26, -21,
	-23, 35, 55, -36, 32, -36, 32, 43, 7, 19,
	54, -28, -31, -30, -30, -30, -30, -32, -32, -32,
	-32, -34, -35, -36, -34, 58, 55, -24, 30, 14,
	50, 50, 50, 50, -36, 54, -36, -36, 8, 55,
	58, 62, 58, -25, 33, 53, -36, -36, -36, -36,
	-36, 55, 55, 55, 55, 55, -35, 53, 13, 18,
	59, 59, 59, 59, 53, 53, 53, 53, 55, 55,
	55, 55,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 5, 6, 7, 8, 9,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	20, 21, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 35, 0, 0, 0, 0, 50, 51,
	0, 91, 0, 0, 0, 0, 38, 0, 0, 0,
	0, 0, 0, 55, 0, 0, 36, 0, 0, 0,
	0, 0, 41, 0, 0, 44, 0, 0, 0, 22,
	28, 29, 30, 0, 0, 0, 33, 34, 0, 39,
	55, 0, 0, 0, 43, 45, 0, 0, 0, 0,
	32, 54, 64, 65, 67, 69, 0, 71, 76, 81,
	0, 0, 84, 85, 86, 0, 0, 59, 40, 52,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 70, 0, 0, 0, 0, 0, 0, 0, 0,
	61, 0, 42, 0, 0, 0, 0, 0, 0, 0,
	0, 66, 68, 72, 73, 74, 75, 77, 78, 79,
	80, 0, 88, 90, 0, 87, 37, 63, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 31,
	82, 0, 83, 53, 0, 60, 56, 0, 0, 0,
	0, 23, 24, 25, 26, 27, 89, 62, 57, 58,
	0, 0, 0, 0, 0, 0, 0, 0, 46, 47,
	48, 49,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	57, 58, 56, 3, 62, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 55,
	60, 59, 61,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.ParseTree{Commands: yyDollar[1].nodeList}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[2].nodeList...)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{yyDollar[1].node}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.ArchiveProjectStmt{Project: yyDollar[3].str}
		}
	case 23:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: yyDollar[8].str, StringLiteral: false}
		}
	case 24:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Set, Value: yyDollar[8].str, StringLiteral: true}
		}
	case 25:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Add, Value: yyDollar[8].str}
		}
	case 26:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Drop, Value: yyDollar[8].str}
		}
	case 27:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.AlterProjectStmt{Project: yyDollar[3].str, Property: yyDollar[6].str, Action: ast.Drop, Value: "*"}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateFundStmt{Fund: yyDollar[3].str}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateProjectStmt{Project: yyDollar[3].str}
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateSetStmt{Set: yyDollar[3].str}
		}
	case 31:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.CreateUserStmt{User: yyDollar[3].str, EncryptedPassword: yyDollar[7].str}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.DeleteStmt{From: yyDollar[3].str, Where: yyDollar[4].node}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DropProjectStmt{Project: yyDollar[3].str}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DropSetStmt{Set: yyDollar[3].str}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ""}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: yyDollar[2].str}
		}
	case 37:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.InsertStmt{Into: yyDollar[3].str, Query: yyDollar[6].node}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.PingStmt{}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{AttrList: yyDollar[2].node, Query: yyDollar[3].node}
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.SelectVersionStmt{}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: yyDollar[2].str}
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: yyDollar[2].str, In: yyDollar[5].str}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "project", Name: yyDollar[3].str}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "projects"}
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Type: "projects", Archived: true}
		}
	case 46:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: yyDollar[4].str, Value: yyDollar[6].str, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 47:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: yyDollar[4].str, ValueNull: true, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 48:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: "fund", Value: yyDollar[6].str, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 49:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Set: yyDollar[2].str, Attr: "fund", ValueNull: true, IDAttr: yyDollar[8].str, IDValue: &ast.Number{Value: yyDollar[10].str}}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: yyDollar[1].str}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "*"}
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "count(*)"}
		}
	case 53:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.QueryClause{From: yyDollar[2].str, Where: yyDollar[3].node, Order: yyDollar[4].node, Limit: yyDollar[5].node, Offset: yyDollar[6].node}
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{Valid: true, Condition: yyDollar[2].node}
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: true}
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{}
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{Valid: true, Count: yyDollar[2].str}
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{}
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{Valid: true, Start: yyDollar[2].str}
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.AndExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.NotExpr{Expr: yyDollar[2].node}
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.EqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LikeExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ILikeExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NotEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FilterExpr{ExprList: yyDollar[3].nodeList}
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.TagExpr{ExprList: yyDollar[3].nodeList}
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: yyDollar[1].str}
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SLiteral{Value: yyDollar[1].str}
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Number{Value: yyDollar[1].str}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ParenExpr{Expr: yyDollar[2].node}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{&ast.Name{Value: yyDollar[1].str}}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = strings.ToLower(yyDollar[1].str)
		}
	}
	goto yystack /* stack new state and value */
}
