// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"github.com/indexdata/ccms/cmd/ccd/ast"
)

type yySymType struct {
	yys      int
	node     ast.Node
	str      string
	nodeList []ast.Node
}

const GT_OR_EQUAL = 57346
const LT_OR_EQUAL = 57347
const NOT_EQUAL = 57348
const AND = 57349
const ASC = 57350
const BY = 57351
const CREATE = 57352
const DESC = 57353
const FILTER = 57354
const FROM = 57355
const INFO = 57356
const INSERT = 57357
const INTO = 57358
const LIMIT = 57359
const NOT = 57360
const OFFSET = 57361
const OR = 57362
const ORDER = 57363
const PING = 57364
const RETRIEVE = 57365
const SELECT = 57366
const SET = 57367
const SHOW = 57368
const TAG = 57369
const WHERE = 57370
const IDENT = 57371
const NUMBER = 57372
const SLITERAL = 57373

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"GT_OR_EQUAL",
	"LT_OR_EQUAL",
	"NOT_EQUAL",
	"AND",
	"ASC",
	"BY",
	"CREATE",
	"DESC",
	"FILTER",
	"FROM",
	"INFO",
	"INSERT",
	"INTO",
	"LIMIT",
	"NOT",
	"OFFSET",
	"OR",
	"ORDER",
	"PING",
	"RETRIEVE",
	"SELECT",
	"SET",
	"SHOW",
	"TAG",
	"WHERE",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"';'",
	"'*'",
	"'='",
	"'<'",
	"'>'",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 105

var yyAct = [...]int8{
	52, 84, 47, 43, 41, 83, 48, 44, 93, 92,
	50, 91, 92, 87, 21, 24, 46, 26, 69, 50,
	28, 67, 66, 68, 36, 51, 34, 23, 54, 53,
	62, 35, 18, 17, 51, 55, 23, 54, 53, 23,
	32, 31, 88, 22, 55, 27, 25, 38, 73, 23,
	29, 16, 64, 65, 63, 40, 59, 72, 61, 74,
	70, 57, 19, 75, 77, 78, 30, 58, 76, 85,
	85, 79, 80, 81, 82, 86, 10, 60, 1, 33,
	11, 12, 89, 49, 45, 90, 42, 71, 15, 56,
	13, 39, 14, 85, 94, 37, 20, 8, 7, 6,
	9, 5, 4, 3, 2,
}

var yyPact = [...]int16{
	66, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	26, 1, 46, 10, 20, 14, 20, -1000, 13, 20,
	53, -1000, -1000, -1000, 9, -1000, 8, -1000, 53, -6,
	20, -1000, -1000, -8, -1000, 19, -1000, 34, -2, 44,
	58, -1000, 36, 70, -1000, 24, -2, 17, -1000, -1000,
	-14, -19, -1000, -1000, -1000, -2, 38, 18, 20, -2,
	-2, 7, 7, -1000, 7, 7, 7, 7, 20, 20,
	-25, -1000, 12, -1000, 74, 70, -1000, 17, 17, -1000,
	-1000, -1000, -1000, -27, -1000, -1000, -30, -1000, -1000, -1000,
	-1000, -1000, 20, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 104, 103, 102, 101, 100, 99, 98, 97, 96,
	50, 95, 91, 89, 87, 4, 86, 3, 84, 2,
	7, 6, 83, 5, 1, 0, 78,
}

var yyR1 = [...]int8{
	0, 26, 1, 2, 2, 2, 2, 2, 2, 3,
	4, 4, 6, 5, 7, 8, 9, 9, 10, 11,
	11, 12, 12, 12, 12, 13, 13, 14, 14, 15,
	16, 16, 17, 17, 20, 20, 18, 18, 18, 19,
	19, 19, 19, 19, 21, 21, 21, 22, 22, 22,
	22, 23, 23, 24, 25,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 4,
	2, 3, 5, 2, 4, 3, 1, 1, 6, 2,
	0, 3, 4, 4, 0, 2, 0, 2, 0, 1,
	1, 3, 1, 3, 1, 2, 1, 3, 3, 1,
	3, 3, 3, 3, 1, 4, 4, 1, 1, 1,
	3, 1, 3, 1, 1,
}

var yyChk = [...]int16{
	-1000, -26, -1, -2, -3, -4, -6, -7, -8, -5,
	10, 14, 15, 24, 26, 22, 25, 32, 31, 16,
	-9, -25, 33, 29, -25, 32, -25, 32, -25, -10,
	13, 32, 32, -10, 32, -25, 32, -11, 28, -12,
	21, -15, -16, -17, -20, -18, 18, -19, -21, -22,
	12, 27, -25, 31, 30, 37, -13, 17, 9, 20,
	7, 34, 6, -20, 35, 36, 5, 4, 37, 37,
	-15, -14, 19, 30, -25, -17, -20, -19, -19, -21,
	-21, -21, -21, -23, -24, -25, -23, 38, 30, 8,
	11, 38, 39, 38, -24,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	0, 0, 0, 0, 0, 0, 0, 10, 0, 0,
	0, 16, 17, 54, 0, 13, 0, 11, 0, 0,
	0, 15, 9, 0, 14, 20, 12, 24, 0, 26,
	0, 19, 29, 30, 32, 34, 0, 36, 39, 44,
	0, 0, 47, 48, 49, 0, 28, 0, 0, 0,
	0, 0, 0, 35, 0, 0, 0, 0, 0, 0,
	0, 18, 0, 25, 21, 31, 33, 37, 38, 40,
	41, 42, 43, 0, 51, 53, 0, 50, 27, 22,
	23, 45, 0, 46, 52,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	37, 38, 33, 3, 39, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 32,
	35, 34, 36,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateSetStmt{SetName: yyDollar[3].str}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ""}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: yyDollar[2].str}
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.InsertStmt{Into: yyDollar[3].str, Query: yyDollar[4].node}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.PingStmt{}
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{AttrList: yyDollar[2].node, Query: yyDollar[3].node}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Name: yyDollar[2].str}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: yyDollar[1].str}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "*"}
		}
	case 18:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.QueryClause{From: yyDollar[2].str, Where: yyDollar[3].node, Order: yyDollar[4].node, Limit: yyDollar[5].node, Offset: yyDollar[6].node}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{Valid: true, Condition: yyDollar[2].node}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: true}
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{Valid: true, Count: yyDollar[2].str}
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{Valid: true, Start: yyDollar[2].str}
		}
	case 28:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.AndExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.NotExpr{Expr: yyDollar[2].node}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.EqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NotEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FilterExpr{ExprList: yyDollar[3].nodeList}
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.TagExpr{ExprList: yyDollar[3].nodeList}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: yyDollar[1].str}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SLiteral{Value: yyDollar[1].str}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Number{Value: yyDollar[1].str}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ParenExpr{Expr: yyDollar[2].node}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{&ast.Name{Value: yyDollar[1].str}}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	}
	goto yystack /* stack new state and value */
}
