// Code generated by goyacc -l -o gram.go gram.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"github.com/indexdata/ccms/cmd/ccd/ast"
)

type yySymType struct {
	yys      int
	node     ast.Node
	str      string
	nodeList []ast.Node
}

const GT_OR_EQUAL = 57346
const LT_OR_EQUAL = 57347
const NOT_EQUAL = 57348
const AND = 57349
const ASC = 57350
const BY = 57351
const CREATE = 57352
const DELETE = 57353
const DESC = 57354
const DROP = 57355
const FILTER = 57356
const FROM = 57357
const INFO = 57358
const INSERT = 57359
const INTO = 57360
const LIMIT = 57361
const NOT = 57362
const OFFSET = 57363
const OR = 57364
const ORDER = 57365
const PING = 57366
const RETRIEVE = 57367
const SELECT = 57368
const SET = 57369
const SHOW = 57370
const TAG = 57371
const WHERE = 57372
const IDENT = 57373
const NUMBER = 57374
const SLITERAL = 57375

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"GT_OR_EQUAL",
	"LT_OR_EQUAL",
	"NOT_EQUAL",
	"AND",
	"ASC",
	"BY",
	"CREATE",
	"DELETE",
	"DESC",
	"DROP",
	"FILTER",
	"FROM",
	"INFO",
	"INSERT",
	"INTO",
	"LIMIT",
	"NOT",
	"OFFSET",
	"OR",
	"ORDER",
	"PING",
	"RETRIEVE",
	"SELECT",
	"SET",
	"SHOW",
	"TAG",
	"WHERE",
	"IDENT",
	"NUMBER",
	"SLITERAL",
	"';'",
	"'*'",
	"'='",
	"'<'",
	"'>'",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 122

var yyAct = [...]int8{
	63, 93, 58, 54, 41, 92, 59, 55, 45, 52,
	103, 102, 101, 102, 61, 96, 79, 77, 76, 61,
	57, 31, 34, 78, 72, 36, 37, 38, 67, 62,
	40, 33, 65, 64, 62, 97, 33, 65, 64, 66,
	51, 33, 49, 50, 66, 32, 15, 16, 47, 17,
	74, 75, 18, 19, 71, 28, 27, 44, 43, 68,
	22, 39, 20, 35, 21, 73, 109, 106, 33, 46,
	14, 26, 81, 84, 86, 87, 80, 24, 85, 94,
	94, 88, 89, 90, 91, 95, 48, 83, 69, 105,
	99, 29, 42, 25, 110, 70, 100, 1, 111, 60,
	56, 107, 4, 94, 108, 53, 23, 104, 98, 82,
	30, 12, 11, 10, 13, 9, 8, 7, 6, 3,
	5, 2,
}

var yyPact = [...]int16{
	36, -1000, -1000, 36, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 50, 78, 44, 22, 73,
	10, 37, 29, -1000, 37, 37, 37, -1000, 27, 37,
	77, -1000, -1000, -1000, 24, -1000, 23, 39, 14, -1000,
	60, 8, 37, -1000, -1000, 6, 0, -1000, -7, -1000,
	39, -1000, -1000, 66, 88, -1000, 18, 0, 13, -1000,
	-1000, -16, -23, -1000, -1000, -1000, 0, 77, 64, 0,
	0, 5, 5, -1000, 5, 5, 5, 5, 37, 37,
	-25, 1, 71, 87, 88, -1000, 13, 13, -1000, -1000,
	-1000, -1000, -28, -1000, -1000, -30, -1000, -1000, 68, 35,
	37, -1000, 37, -1000, -1000, 34, -1000, 86, -1000, -1000,
	-1000, -1000,
}

var yyPgo = [...]int8{
	0, 121, 120, 102, 119, 118, 117, 116, 115, 114,
	113, 112, 111, 110, 4, 8, 109, 108, 107, 9,
	105, 3, 100, 2, 7, 6, 99, 5, 1, 0,
	97,
}

var yyR1 = [...]int8{
	0, 30, 1, 4, 4, 3, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 5, 6, 7, 8, 8,
	10, 9, 11, 12, 13, 13, 14, 15, 15, 16,
	16, 16, 16, 17, 17, 18, 18, 19, 20, 20,
	21, 21, 24, 24, 22, 22, 22, 23, 23, 23,
	23, 23, 25, 25, 25, 26, 26, 26, 26, 27,
	27, 28, 29,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 4, 5, 4, 2, 3,
	7, 2, 4, 3, 1, 1, 6, 2, 0, 3,
	4, 4, 0, 2, 0, 2, 0, 1, 1, 3,
	1, 3, 1, 2, 1, 3, 3, 1, 3, 3,
	3, 3, 1, 4, 4, 1, 1, 1, 3, 1,
	3, 1, 1,
}

var yyChk = [...]int16{
	-1000, -30, -1, -4, -3, -2, -5, -6, -7, -8,
	-10, -11, -12, -9, 34, 10, 11, 13, 16, 17,
	26, 28, 24, -3, 27, 15, 27, 34, 33, 18,
	-13, -29, 35, 31, -29, 34, -29, -29, -29, 34,
	-29, -14, 15, 34, 34, -15, 30, 34, 26, 34,
	-29, 34, -19, -20, -21, -24, -22, 20, -23, -25,
	-26, 14, 29, -29, 33, 32, 39, 35, -15, 22,
	7, 36, 6, -24, 37, 38, 5, 4, 39, 39,
	-19, -14, -16, 23, -21, -24, -23, -23, -25, -25,
	-25, -25, -27, -28, -29, -27, 40, 34, -17, 19,
	9, 40, 41, 40, -18, 21, 32, -29, -28, 32,
	8, 12,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 5, 6, 7, 8, 9,
	10, 11, 12, 13, 14, 0, 0, 0, 0, 0,
	0, 0, 0, 4, 0, 0, 0, 18, 0, 0,
	0, 24, 25, 62, 0, 21, 0, 28, 0, 19,
	0, 0, 0, 23, 15, 0, 0, 17, 0, 22,
	28, 16, 27, 37, 38, 40, 42, 0, 44, 47,
	52, 0, 0, 55, 56, 57, 0, 0, 32, 0,
	0, 0, 0, 43, 0, 0, 0, 0, 0, 0,
	0, 0, 34, 0, 39, 41, 45, 46, 48, 49,
	50, 51, 0, 59, 61, 0, 58, 20, 36, 0,
	0, 53, 0, 54, 26, 0, 33, 29, 60, 35,
	30, 31,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	39, 40, 35, 3, 41, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 34,
	37, 36, 38,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.ParseTree{Commands: yyDollar[1].nodeList}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[2].nodeList...)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{yyDollar[1].node}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 15:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CreateSetStmt{SetName: yyDollar[3].str}
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.DeleteStmt{From: yyDollar[3].str, Where: yyDollar[4].node}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DropSetStmt{SetName: yyDollar[3].str}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: ""}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.InfoStmt{Topic: yyDollar[2].str}
		}
	case 20:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.InsertStmt{Into: yyDollar[3].str, Query: yyDollar[6].node}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.PingStmt{}
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{AttrList: yyDollar[2].node, Query: yyDollar[3].node}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ShowStmt{Name: yyDollar[2].str}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: yyDollar[1].str}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SelectAttrList{Attr: "*"}
		}
	case 26:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.QueryClause{From: yyDollar[2].str, Where: yyDollar[3].node, Order: yyDollar[4].node, Limit: yyDollar[5].node, Offset: yyDollar[6].node}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{Valid: true, Condition: yyDollar[2].node}
		}
	case 28:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.WhereClause{}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: false}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{Valid: true, Attr: yyDollar[3].str, Desc: true}
		}
	case 32:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OrderClause{}
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{Valid: true, Count: yyDollar[2].str}
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.LimitClause{}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{Valid: true, Start: yyDollar[2].str}
		}
	case 36:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &ast.OffsetClause{}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.OrExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.AndExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.NotExpr{Expr: yyDollar[2].node}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.EqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NotEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.LessThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.GreaterThanOrEqualExpr{Expr1: yyDollar[1].node, Expr2: yyDollar[3].node}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FilterExpr{ExprList: yyDollar[3].nodeList}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.TagExpr{ExprList: yyDollar[3].nodeList}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Name{Value: yyDollar[1].str}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.SLiteral{Value: yyDollar[1].str}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Number{Value: yyDollar[1].str}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ParenExpr{Expr: yyDollar[2].node}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = yyDollar[1].nodeList
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodeList = append(yyDollar[1].nodeList, yyDollar[3].nodeList...)
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodeList = []ast.Node{&ast.Name{Value: yyDollar[1].str}}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	}
	goto yystack /* stack new state and value */
}
