==== alter project

Change the definition of a project

[source,subs="verbatim,quotes"]
----
alter project `*_project_name_*`
    `*_action_*`

where `*_action_*` is one of:

    alter property `*_property_name_*` set { `*_value_*` | `*'_value_'*` }
    alter property `*_property_name_*` add `*_subvalue_*`
    alter property `*_property_name_*` drop { `*_subvalue_*` | all }
----

[discrete]
===== Description

The `alter project` command changes the definition of a project.

The `alter property` clause changes a property in the project's
metadata.  The `set` action is used for single-value properties, while
`add` and `drop` are for composite properties.

[discrete]
===== Parameters

[frame=none,grid=none,cols="1,2"]
|===
|`*_project_name_*`
|The name of the project.

|`*_property_name_*`
|The name of the property in the project metadata.

|`*_value_*` +
`*'_value_'*`
|The value of a single-value property.

|`*_subvalue_*`
|A subvalue in a composite property.
|===

[discrete]
===== Properties

[%header,width=75%,cols="3,3,10"]
|===
|Property
|Type
|Value

|`title`
|single-value
|text

|`action`
|single-value
|action name (`acquire`, `retire`, `digitize`, `move`, `other`)

|`mou_link`
|single-value
|text

|`funds`
|composite
|fund name (`coalition_slavic_lit`, `palci_cultural`)

|`origins`
|composite
|location name (`clockss`, `lehigh`, `nyu`)

|`destinations`
|composite
|location name

|`tracks`
|composite
|track name (`offsite`, `reserve`, `stacks`)
|===

[discrete]
===== Examples

Set the title of project `myproj` to `My Project`:

----
alter project myproj alter property title set 'My Project';
----

Add a fund `palci_cultural` to the project:

----
alter project myproj alter property funds add palci_cultural;
----
