== Reference

=== Commands

include::createset.adoc[]

include::insert.adoc[]

include::select.adoc[]

include::show.adoc[]

=== Queries

==== Value expressions

The `where` clause in a query is followed by a search condition.  This
condition is a Boolean expression consisting of operators and
operands.

The supported operators, in order of precedence, are:

[%header,width=75%,cols="4,3,5"]
|===
|Operator
|Associativity
|Description

|`=` `<>` `<` `>` `\<=` `>=`
|
|comparison operators

|`not`
|right
|logical negation

|`and`
|left
|logical conjunction

|`or`
|left
|logical disjunction
|===

Parentheses may be used to override these precedence rules.

Supported operand types are:

[%header,width=75%,cols="3,4,5"]
|===
|Operand type
|Example
|Description

|name
|`author`
|attribute name

|string literal
|`'Thomas à Kempis'`
|string constant

|number
|`33`
|numeric constant
|===

=== Protocol

Non-query commands such as `create set` return a diagnostic status:

[source,json]
----
{
  "commands": "create set test.myset;"
}
----

[source,json]
----
{
  "results": [
    {
      "status": "create set"
    }
  ]
}
----

The status may be an error:

[source,json]
----
{
  "results": [
    {
      "status": "error",
      "message": "set test.myset already exists"
    }
  ]
}
----

Query commands such as `select` also return tabular data sets, with
the attribute names described under `"fields"`, e.g.:

[source,json]
----
{
  "commands": "select id from test.myset limit 2;"
}
----

[source,json]
----
{
  "results": [
    {
      "status": "select",
      "fields": [
        {
          "name": "id",
          "type": "bigint"
        }
      ],
      "data": [
        [
          41
        ],
        [
          63
        ]
      ]
    }
  ]
}
----

NOTE:  Selecting individual attributes, as in the example above, is
not yet supported.  However, `select *` is supported.

Multiple commands can be combined in a single request, separated by
semicolons:

[source,json]
----
{
  "commands": "create set test.myset; create set test.myset2;"
}
----

