==== select

Retrieve objects from a set

[source,subs="verbatim,quotes"]
----
select *
    from `*_set_name_*`
    [ where `*_condition_*` ]
    [ limit `*_count_*` ]
----

[discrete]
===== Description

The `select` command retrieves a list of objects from a set according
to specified criteria.

[discrete]
===== Parameters

The first argument specifies `*` meaning all available attributes.

[discrete]
====== from

The `from` clause specifies the desired set that will be the source of
data.

[discrete]
====== where

The `where` clause specifies a condition in the form of a Boolean
expression.  Only objects that satisfy this condition will be
retrieved.

NOTE:  Currently the only supported form of `*_condition_*` is
`_attribute_ = '_value_'`.

[discrete]
====== limit

The `limit` clause specifies a maximum number of objects that will be
returned.

NOTE:  At present the CCMS server returns a maximum of 30 records to
the client, even if a higher maximum is specified using `limit`.  This
maximum applies only to the `select` command; it does not apply to the
`insert` command, which does not return records to the client.

[discrete]
===== Examples

To retrieve all fields of items in stock:

----
select * from reserve where availability = 'In stock';
----

