== Server administration

=== System requirements

==== Hardware requirements

This section will contain system hardware requirements.

==== Software requirements

* Operating system: Linux
* Database system: https://www.postgresql.org/[PostgreSQL] 18 or later
* To build from source:
** https://go.dev/[Go] 1.21
** https://www.gnu.org/software/bash/[bash]

=== Building the software

It is suggested that a `ccms` user be created and the server run by
that user, for example, in `/home/ccms`.

To build CCMS, first set the `GOPATH` environment variable to specify
a path that can serve as the build workspace for Go, e.g.:

[source,bash]
----
export GOPATH=$HOME/go
----

Then to build the server:

[source,bash]
----
./build
----

The `build` script creates a `bin/` subdirectory and builds the `ccd`
server and `ccc` client executables there:

[source,bash]
----
./bin/ccd help

./bin/ccc help
----

In general running `ccd` takes the form:

----
ccd <command> <arguments>
----

Some typical commands are:

* `init` initializes a new CCMS instance
* `start` starts the server
* `stop` shuts down the server
* `version` prints the CCMS version

For more infomation about a specific command:

----
ccd help <command>
----

=== Server configuration

The `ccd` server makes use of local storage in a *data directory*
which is created using `ccd` with the `init` command.  In this example
we will create the data directory as `data/`:

[source,bash]
----
ccd init -D data
----

This will also create a file `ccd.conf` in the data directory with the
following structure:

[source,ini,subs="verbatim,quotes"]
----
[main]
host = _host name of the PostgreSQL server_
port = _port number of the PostgreSQL server_
database = _database name_
user = _database user that is the owner of the database_
password = _password of user_
sslmode = _should be set to "require" or stronger option_
----

This file should be edited to add database connection parameters, for
example:

[source,ini,subs="verbatim,quotes"]
----
[main]
host = ccms.indexdata.com
port = 5432
database = ccms
user = ccms
password = w6bqYkFWm4rpGR5mCtFw
sslmode = require
----

The `ccd` server will assume that the database, superuser, and
systemuser defined here already exist; so they should be created
before continuing.

=== Upgrading from a previous version

Upgrading from a previous version of ccms is not currently supported.

=== Running the server

To start the server:

[source,bash]
----
nohup ccd start -D data -l ccd.log &
----

To stop the server:

[source,bash]
----
ccd stop -D data
----

The server can be set up to run with systemd via a file such as
`/etc/systemd/system/ccms.service`, for example:

[source,ini]
----
[Unit]
Description=CCMS
After=network.target remote-fs.target

[Service]
Type=simple
User=ccms
ExecStart=/bin/bash -ce "exec /home/ccms/bin/ccd start -D /home/ccms/data -l /home/ccms/ccd.log"
Restart=on-abort

[Install]
WantedBy=multi-user.target
----

Then:

----
systemctl enable ccms

systemctl start ccms
----
