== User guide

This section will contain an overview of using the system.

=== Getting started

CCMS can be accessed in two ways: programmatically via a service API,
or by using the `ccm` client.  This section will introduce CCMS
commands using the `ccm` client.  A `ccm` session looks something
like:

----
$ ccm
> list sets
allobjects
myset
reserve
> retrieve (id) from myset
053e4063-d70c-4a41-a968-e6900e6b47d5
ac256496-111a-4e13-9d3b-a55ac3d0f676
>
----

=== Retrieving objects

We can view objects in the "reserve" which is a predefined set that
contains all available objects.

----
> retrieve (id) from reserve limit 5
c644d186-399b-4f80-b92b-c6c38d69db07
ac256496-111a-4e13-9d3b-a55ac3d0f676
f43bfb56-fd34-4fd3-b944-dca46e22751f
053e4063-d70c-4a41-a968-e6900e6b47d5
dd7de2bf-b5e1-452a-97f6-bafa586e67c5
----

To look at a specific object in detail:

----
> retrieve (all) from reserve where id = "053e4063-d70c-4a41-a968-e6900e6b47d5"
----

We can create a new set called "myset" and begin adding objects of
interest to it:

----
> create set myset
> insert into myset from reserve where id = "053e4063-d70c-4a41-a968-e6900e6b47d5"
insert 1
> insert into myset from reserve where id = "ac256496-111a-4e13-9d3b-a55ac3d0f676"
insert 1
----

To list the objects in myset:

----
> retrieve (id) from myset
053e4063-d70c-4a41-a968-e6900e6b47d5
ac256496-111a-4e13-9d3b-a55ac3d0f676
----

We can create a set that contains all available objects, with the idea
of subsequently removing unneeded objects.  This may take a minute to
run due to the large number of objects:

----
> create set allobjects
> insert into allobjects from reserve
insert 42698273
----

----
> retrieve (id) from allobjects limit 5
c644d186-399b-4f80-b92b-c6c38d69db07
ac256496-111a-4e13-9d3b-a55ac3d0f676
f43bfb56-fd34-4fd3-b944-dca46e22751f
053e4063-d70c-4a41-a968-e6900e6b47d5
dd7de2bf-b5e1-452a-97f6-bafa586e67c5
----

To list all sets:

----
> list sets
allobjects
myset
reserve
----
