package server

import (
	"context"
	"errors"
	"fmt"

	"github.com/indexdata/ccms/internal/global"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type createTableFunc func(pgx.Tx) error

type systemTableDef struct {
	table  string
	create createTableFunc
}

var systemTables = []systemTableDef{
	{table: "init", create: createTableInit},
	{table: "md", create: createTableMD},
	{table: "attr", create: createTableAttr},
	{table: "reserve", create: createTableReserve},
}

func createTableInit(tx pgx.Tx) error {
	q := "create table " + global.SystemSchema + ".init (" +
		"dbversion integer not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table "+global.SystemSchema+".init: %v", err)
	}
	q = "insert into " + global.SystemSchema + ".init (dbversion) values (0)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table "+global.SystemSchema+".init: %v", err)
	}
	return nil
}

func createTableMD(tx pgx.Tx) error {
	q := "create table " + global.SystemSchema + ".md (" +
		"id bigint primary key generated by default as identity," +
		"identifier uuid not null unique," +
		"retrieved timestamptz not null," +
		"date_stamp date not null," +
		"data text not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table "+global.SystemSchema+".md: %v", err)
	}
	return nil
}

func createTableAttr(tx pgx.Tx) error {
	q := "create table " + global.SystemSchema + ".attr (" +
		"id bigint primary key," +
		"author text," +
		"title text)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table "+global.SystemSchema+".attr: %v", err)
	}
	q = "create index on " + global.SystemSchema + ".attr (author)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on "+global.SystemSchema+".attr (author): %v", err)
	}
	q = "create index on " + global.SystemSchema + ".attr (title)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on "+global.SystemSchema+".attr (title): %v", err)
	}
	return nil
}

func createTableReserve(tx pgx.Tx) error {
	q := "create table " + global.SystemSchema + ".reserve (" +
		"id bigint primary key)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table "+global.SystemSchema+".reserve: %v", err)
	}
	return nil
}

func initialize(dp *pgxpool.Pool) error {
	exists, err := initSchemaExists(dp)
	if err != nil {
		return fmt.Errorf("checking if database initialized: %w", err)
	}
	if !exists {
		if err = createSystemSchema(dp); err != nil {
			return err
		}
	} else {
		// TODO check that database version is compatible;
		// for now we assume it is compatible
	}
	return nil
}

func initSchemaExists(dp *pgxpool.Pool) (bool, error) {
	var err error
	var q = "SELECT 1 FROM pg_namespace WHERE nspname=$1"
	var n int32
	err = dp.QueryRow(context.TODO(), q, global.SystemSchema).Scan(&n)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
		return false, nil
	case err != nil:
		return false, err
	default:
		return true, nil
	}
}

func createSystemSchema(dp *pgxpool.Pool) error {
	tx, err := dp.Begin(context.TODO())
	if err != nil {
		return err
	}
	defer tx.Rollback(context.TODO())

	var q = "create schema " + global.SystemSchema
	_, err = tx.Exec(context.TODO(), q)
	if err != nil {
		return fmt.Errorf("creating schema: "+global.SystemSchema+": %v", err)
	}

	for _, t := range systemTables {
		if err = t.create(tx); err != nil {
			return fmt.Errorf("creating table %s.%s: %v", global.SystemSchema, t.table, err)
		}
	}

	if err = tx.Commit(context.TODO()); err != nil {
		return fmt.Errorf("initializing system database: committing changes: %w", err)
	}
	return nil
}
