package catalog

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Catalog struct {
	mu   sync.Mutex
	sets map[string]struct{}
	dp   *pgxpool.Pool
}

func Initialize(dp *pgxpool.Pool) (*Catalog, error) {
	exists, err := initSchemaExists(dp)
	if err != nil {
		return nil, fmt.Errorf("checking if database initialized: %w", err)
	}
	if !exists {
		if err = createSystemSchema(dp); err != nil {
			return nil, err
		}
	} else {
		// TODO check that database version is compatible;
		// for now we assume it is compatible
	}
	c := &Catalog{dp: dp}
	if err := c.initSets(); err != nil {
		return nil, err
	}

	return c, nil
}

type createTableFunc func(pgx.Tx) error

type systemTableDef struct {
	table  string
	create createTableFunc
}

var systemTables = []systemTableDef{
	{table: "init", create: createTableInit},
	{table: "md", create: createTableMD},
	{table: "attr", create: createTableAttr},
	{table: "reserve", create: createTableReserve},
	{table: "project", create: createTableProject},
	{table: "sets", create: createTableSets},
}

func createTableInit(tx pgx.Tx) error {
	q := "create table ccms.init (" +
		"dbversion integer not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.init: %v", err)
	}
	q = "insert into ccms.init (dbversion) values (0)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.init: %v", err)
	}
	return nil
}

func createTableMD(tx pgx.Tx) error {
	q := "create table ccms.md (" +
		"id bigint primary key generated by default as identity," +
		"identifier uuid not null unique," +
		"retrieved timestamptz not null," +
		"date_stamp date not null," +
		"data text not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.md: %v", err)
	}
	return nil
}

func createTableAttr(tx pgx.Tx) error {
	q := "create table ccms.attr (" +
		"id bigint primary key," +
		"author text," +
		"title text," +
		"full_vendor_name text," +
		"availability text)"
		//"place_of_publication text)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.attr: %v", err)
	}
	q = "create index on ccms.attr (author)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (author): %v", err)
	}
	q = "create index on ccms.attr (title)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (title): %v", err)
	}
	q = "create index on ccms.attr (full_vendor_name)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (full_vendor_name): %v", err)
	}
	q = "create index on ccms.attr (availability)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (availability): %v", err)
	}
	return nil
}

func createTableReserve(tx pgx.Tx) error {
	q := "create table ccms.reserve (" +
		"id bigint primary key)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.reserve: %v", err)
	}
	return nil
}

func createTableProject(tx pgx.Tx) error {
	q := "create table ccms.project (" +
		"projname text primary key)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.project: %v", err)
	}
	q = "insert into ccms.project (projname) values ('test')"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.project: %v", err)
	}
	q = "create schema test"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating schema test: %v", err)
	}
	return nil
}

func createTableSets(tx pgx.Tx) error {
	q := "create table ccms.sets (" +
		"setname text primary key)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.sets: %v", err)
	}
	q = "insert into ccms.sets (setname) values ('ccms.reserve')"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.sets: %v", err)
	}
	return nil
}

func initSchemaExists(dp *pgxpool.Pool) (bool, error) {
	var err error
	var q = "SELECT 1 FROM pg_namespace WHERE nspname=$1"
	var n int32
	err = dp.QueryRow(context.TODO(), q, "ccms").Scan(&n)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
		return false, nil
	case err != nil:
		return false, err
	default:
		return true, nil
	}
}

func createSystemSchema(dp *pgxpool.Pool) error {
	tx, err := dp.Begin(context.TODO())
	if err != nil {
		return err
	}
	defer tx.Rollback(context.TODO())

	var q = "create schema ccms"
	_, err = tx.Exec(context.TODO(), q)
	if err != nil {
		return fmt.Errorf("creating schema: ccms: %v", err)
	}

	for _, t := range systemTables {
		if err = t.create(tx); err != nil {
			return fmt.Errorf("creating table ccms.%s: %v", t.table, err)
		}
	}

	if err = tx.Commit(context.TODO()); err != nil {
		return fmt.Errorf("initializing system database: committing changes: %v", err)
	}
	return nil
}
