package catalog

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/indexdata/ccms/cmd/ccd/config"
	"github.com/indexdata/ccms/internal/crypto"
	"github.com/indexdata/ccms/internal/eout"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Catalog struct {
	mu        sync.Mutex
	secretKey []byte
	roles     map[string]roleUsers
	users     map[string]auth
	projects  map[string]struct{}
	sets      map[string]struct{}
	dp        *pgxpool.Pool
}

type roleUsers struct {
	users map[string]struct{}
}

type auth struct {
	superuser bool
	login     bool
	password  string
	salt      []byte
}

func Initialize(program string, dp *pgxpool.Pool, security *config.Security) (*Catalog, error) {
	exists, err := initSchemaExists(dp)
	if err != nil {
		return nil, fmt.Errorf("checking if database initialized: %w", err)
	}
	if !exists {
		if err = createSystemSchema(program, dp, security); err != nil {
			return nil, err
		}
	} else {
		// TODO check that database version is compatible;
		// for now we assume it is compatible
	}
	c := &Catalog{secretKey: security.SecretKey, dp: dp}
	if err := c.initAuth(); err != nil {
		return nil, err
	}
	if err := c.initProjects(); err != nil {
		return nil, err
	}
	if err := c.initRoles(); err != nil {
		return nil, err
	}
	if err := c.initSets(); err != nil {
		return nil, err
	}

	return c, nil
}

type createTableFunc func(pgx.Tx) error

type systemTableDef struct {
	table  string
	create createTableFunc
}

var systemTables = []systemTableDef{
	{table: "init", create: createTableInit},
	{table: "md", create: createTableMD},
	{table: "attr", create: createTableAttr},
	{table: "reserve", create: createTableReserve},
	{table: "acl", create: createTableACL},
	{table: "auth", create: createTableAuth},
	{table: "role", create: createTableRole},
	{table: "role_user", create: createTableRoleUser},
	{table: "project", create: createTableProject},
	{table: "sets", create: createTableSets},
	{table: "fund", create: createTableFund},
	{table: "project_fund", create: createTableProjectFund},
}

func createTableInit(tx pgx.Tx) error {
	q := "create table ccms.init (" +
		"dbversion integer not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.init: %v", err)
	}
	q = "insert into ccms.init (dbversion) values (0)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.init: %v", err)
	}
	return nil
}

func createTableMD(tx pgx.Tx) error {
	q := "create table ccms.md (" +
		"id bigint primary key generated by default as identity," +
		"identifier uuid not null unique," +
		"retrieved timestamptz not null," +
		"date_stamp date not null," +
		"data text not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.md: %v", err)
	}
	return nil
}

func createTableAttr(tx pgx.Tx) error {
	q := "create table ccms.attr (" +
		"id bigint primary key," +
		"author text," +
		"title text," +
		"full_vendor_name text," +
		"availability text)"
		//"place_of_publication text)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.attr: %v", err)
	}
	q = "create index on ccms.attr (author)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (author): %v", err)
	}
	q = "create index on ccms.attr (title)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (title): %v", err)
	}
	q = "create index on ccms.attr (full_vendor_name)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (full_vendor_name): %v", err)
	}
	q = "create index on ccms.attr (availability)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating index on ccms.attr (availability): %v", err)
	}
	return nil
}

func createTableReserve(tx pgx.Tx) error {
	q := "create table ccms.reserve (" +
		"id bigint primary key)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.reserve: %v", err)
	}
	return nil
}

func createTableACL(tx pgx.Tx) error {
	q := "create table ccms.acl (" +
		"id integer primary key generated by default as identity," +
		"objectname text not null," +
		"objecttype char not null check (objecttype IN ('p', 's'))," +
		"privilege char not null check (privilege IN ('r', 'w'))," +
		"rolename text not null," +
		"unique (objectname, objecttype, privilege, rolename))"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.acl: %v", err)
	}
	return nil
}

func createTableAuth(tx pgx.Tx) error {
	q := "create table ccms.auth (" +
		"id integer primary key generated by default as identity," +
		"name text not null unique," +
		"superuser bool," +
		"login bool," +
		"password text not null," +
		"salt text not null)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.auth: %v", err)
	}
	return nil
}

func createTableProject(tx pgx.Tx) error {
	q := "create table ccms.project (" +
		"id integer primary key generated by default as identity," +
		"name text not null unique," +
		"title text," +
		"action text," + // references ccms.action (name)
		"mou_link text)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.project: %v", err)
	}

	q = "insert into ccms.project (name) values ('test')"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.project: %v", err)
	}
	q = "create schema test"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating schema test: %v", err)
	}

	q = "insert into ccms.project (name,title,action,mou_link) values ('palci_slavic','Slavic studies','purchase','https://www.miketaylor.org.uk/dino/pubs/')"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.project: %v", err)
	}
	q = "create schema palci_slavic"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating schema palci_slavic: %v", err)
	}

	q = "insert into ccms.project (name,title,action) values ('east_asia','East Asian studies','purchase')"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.project: %v", err)
	}
	q = "create schema east_asia"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating schema east_asia: %v", err)
	}

	return nil
}

func createTableSets(tx pgx.Tx) error {
	q := "create table ccms.sets (" +
		"setname text primary key)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.sets: %v", err)
	}
	return nil
}

func createTableFund(tx pgx.Tx) error {
	q := "create table ccms.fund (" +
		"id integer primary key generated by default as identity," +
		"name text not null unique," +
		"title text)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.fund: %v", err)
	}

	q = "insert into ccms.fund (name, title) values ('palci_cultural', 'PALCI cultural preservation'), ('coalition_slavic_lit', 'Coalition for Slavic literature')"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.fund: %v", err)
	}

	return nil
}

func createTableProjectFund(tx pgx.Tx) error {
	q := "create table ccms.project_fund (" +
		"project_id integer not null references ccms.project (id)," +
		"fund_id integer not null references ccms.fund (id)," +
		"primary key (project_id, fund_id))"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.project_fund: %v", err)
	}

	q = "insert into ccms.project_fund (project_id, fund_id) values (2, 1), (2, 2)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("writing to table ccms.project_fund: %v", err)
	}

	return nil
}

func createTableRole(tx pgx.Tx) error {
	q := "create table ccms.role (" +
		"id integer primary key generated by default as identity," +
		"name text not null unique)"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.role: %v", err)
	}
	return nil
}

func createTableRoleUser(tx pgx.Tx) error {
	q := "create table ccms.role_user (" +
		"role_id integer not null references ccms.role (id)," +
		"user_id integer not null references ccms.auth (id)," +
		"primary key (role_id, user_id))"
	if _, err := tx.Exec(context.TODO(), q); err != nil {
		return fmt.Errorf("creating table ccms.role_user: %v", err)
	}
	return nil
}

func initSchemaExists(dp *pgxpool.Pool) (bool, error) {
	var err error
	var q = "select 1 from pg_namespace where nspname=$1"
	var n int32
	err = dp.QueryRow(context.TODO(), q, "ccms").Scan(&n)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
		return false, nil
	case err != nil:
		return false, err
	default:
		return true, nil
	}
}

func createSystemSchema(program string, dp *pgxpool.Pool, security *config.Security) error {
	tx, err := dp.Begin(context.TODO())
	if err != nil {
		return err
	}
	defer tx.Rollback(context.TODO())

	var q = "create schema ccms"
	_, err = tx.Exec(context.TODO(), q)
	if err != nil {
		return fmt.Errorf("creating schema: ccms: %v", err)
	}

	for _, t := range systemTables {
		if err = t.create(tx); err != nil {
			return fmt.Errorf("creating table ccms.%s: %v", t.table, err)
		}
	}
	if err = writeAdminUser(tx, security); err != nil {
		return fmt.Errorf("adding admin user: %v", err)
	}

	if err = tx.Commit(context.TODO()); err != nil {
		return fmt.Errorf("initializing system database: committing changes: %v", err)
	}
	return nil
}

func writeAdminUser(tx pgx.Tx, security *config.Security) error {
	eout.Info("setting up new \"admin\" user")
	adminPassword, err := crypto.InputPassword("Password for \"admin\": ", true)
	if err != nil {
		return err
	}
	if strings.TrimSpace(adminPassword) == "" {
		return errors.New("password is required")
	}

	salt := crypto.RandomKey()
	hash := crypto.HashPassword(crypto.HashPassword(adminPassword, nil, nil), salt, security.SecretKey)
	q := "insert into ccms.auth (name, superuser, login, password, salt) values ($1, true, true, $2, $3)"
	if _, err := tx.Exec(context.TODO(), q, "admin", hash, crypto.EncodeToHexString(salt)); err != nil {
		return fmt.Errorf("writing to table ccms.auth: %v", err)
	}

	//// temporary: add nemo user
	salt = crypto.RandomKey()
	hash = crypto.HashPassword(crypto.HashPassword("testpass", nil, nil), salt, security.SecretKey)
	q = "insert into ccms.auth (name, superuser, login, password, salt) values ($1, false, true, $2, $3)"
	if _, err := tx.Exec(context.TODO(), q, "nemo", hash, crypto.EncodeToHexString(salt)); err != nil {
		return fmt.Errorf("writing user \"nemo\" to table ccms.auth: %v", err)
	}
	////

	return nil
}
